name: Build node docker images

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into Docker Hub registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Extract metadata (tags, labels) for Docker public node
      # https://github.com/docker/metadata-action
      - name: Extract Docker public node metadata
        id: meta-public
        uses: docker/metadata-action@v4
        with:
          images: imashonskiy/wavesnode-test
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.event.release.prerelease == false }}

      # Extract metadata (tags, labels) for Docker private node
      # https://github.com/docker/metadata-action
      - name: Extract Docker private node metadata
        id: meta-private
        uses: docker/metadata-action@v4
        with:
          images: imashonskiy/waves-private-node-test

      # Build and push Docker public image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker public image
        id: build-and-push-public
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta-public.outputs.tags }}
          build-args: |
            NODE_TAG=${{ github.event.release.tag_name }}

      # Build and push Docker private image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker private image
        id: build-and-push-private
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta-private.outputs.tags }}
          build-args: |
            NODE_TAG=${{ github.event.release.tag_name }}
            PRIVATE_NODE="true"
            WAVES_NETWORK="custom"
